# -*- coding: utf-8 -*-
"""Restaurant Rating Product.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NeKYfxzphLjgUJCSHNkze4Euxs7HY0-i
"""

# Data Handling
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Machine Learning
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

import warnings
warnings.filterwarnings("ignore")

from google.colab import files

uploaded = files.upload()

df = pd.read_csv(next(iter(uploaded)))

df.head()

print(df.shape)

df.info()

df.describe()

df.isnull().sum()

# Fill numerical columns with median

numerical_columns = df.select_dtypes(include=np.number).columns

for col in numerical_columns:
    df[col].fillna(df[col].median(), inplace=True)


# Fill categorical columns with mode

categorical_columns = df.select_dtypes(include='object').columns

for col in categorical_columns:
    df[col].fillna(df[col].mode()[0], inplace=True)

print("Missing Values After Cleaning")

print(df.isnull().sum())

drop_columns = [
    'Restaurant ID',
    'Restaurant Name',
    'Address',
    'Locality',
    'Locality Verbose'
]

for col in drop_columns:
    if col in df.columns:
        df.drop(col, axis=1, inplace=True)

label_encoder = LabelEncoder()

categorical_columns = df.select_dtypes(include='object').columns

for col in categorical_columns:
    df[col] = label_encoder.fit_transform(df[col])

df.head()

X = df.drop("Aggregate rating", axis=1)

y = df["Aggregate rating"]

X_train, X_test, y_train, y_test = train_test_split(

    X,
    y,
    test_size=0.2,
    random_state=42
)

linear_model = LinearRegression()

linear_model.fit(X_train, y_train)

linear_predictions = linear_model.predict(X_test)

mse = mean_squared_error(y_test, linear_predictions)

rmse = np.sqrt(mse)

mae = mean_absolute_error(y_test, linear_predictions)

r2 = r2_score(y_test, linear_predictions)

print("Linear Regression Results")

print("MAE :", mae)

print("MSE :", mse)

print("RMSE :", rmse)

print("R2 Score :", r2)

tree_model = DecisionTreeRegressor(random_state=42)

tree_model.fit(X_train, y_train)

tree_predictions = tree_model.predict(X_test)

mse = mean_squared_error(y_test, tree_predictions)

rmse = np.sqrt(mse)

mae = mean_absolute_error(y_test, tree_predictions)

r2 = r2_score(y_test, tree_predictions)

print("Decision Tree Results")

print("MAE :", mae)

print("MSE :", mse)

print("RMSE :", rmse)

print("R2 Score :", r2)

comparison = pd.DataFrame({

    "Model":[
        "Linear Regression",
        "Decision Tree"
    ],

    "R2 Score":[

        r2_score(y_test, linear_predictions),

        r2_score(y_test, tree_predictions)

    ]
})

comparison

importance = pd.DataFrame({

    "Feature": X.columns,

    "Importance": tree_model.feature_importances_

})

importance = importance.sort_values(by="Importance", ascending=False)

importance.head(10)

plt.figure(figsize=(10,6))

sns.barplot(

    x="Importance",

    y="Feature",

    data=importance.head(10)

)

plt.title("Top 10 Important Features")

plt.show()

plt.figure(figsize=(8,8))

plt.scatter(y_test, tree_predictions)

plt.xlabel("Actual Rating")

plt.ylabel("Predicted Rating")

plt.title("Actual vs Predicted Ratings")

plt.show()

import joblib

joblib.dump(tree_model, "Restaurant_Rating_Model.pkl")